<?xml version="1.0" encoding="utf-8"?>
<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:BM="http://www.univ-grenoble-alpes.fr/l3miage/BibliothequeMusical"
        targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/BibliothequeMusical"
        elementFormDefault="qualified">

    <!-- Élément racine -->
    <element name="BibliothequeMusical" type="BM:BibliothequeMusicalType">
        <!-- Pour rendre l'identifiant d'un album unique -->
        <key name="AlbumIDkey">
            <selector xpath="BM:album"/>
            <field xpath="@id"/>
        </key>
    </element>

    <!-- Type complexe pour la bibliothèque -->
    <complexType name="BibliothequeMusicalType">
        <sequence>
            <element name="album" type="BM:albumType" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!-- Type complexe pour un album -->
    <complexType name="albumType">
        <sequence>
            <element name="titre" type="string"/>
            <element name="artiste" type="string"/>
            <element name="genre" type="BM:TypeGenre"/>
            <element name="chansons" type="BM:listeChansonsType"/>
        </sequence>
        <attribute name="id" type="integer" use="required"/>
    </complexType>

    <!-- Type simple pour le genre musical -->
    <simpleType name="TypeGenre">
        <restriction base="string">
            <enumeration value="Rap"/>
            <enumeration value="Rock"/>
            <enumeration value="Pop"/>
            <enumeration value="Jazz"/>
            <enumeration value="Classique"/>
        </restriction>
    </simpleType>

    <!-- Type complexe pour la liste de chansons -->
    <complexType name="listeChansonsType">
        <sequence>
            <element name="chanson" type="BM:chansonType" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!-- Type complexe pour une chanson -->
    <complexType name="chansonType">
        <sequence>
            <element name="titre" type="string"/>
            <element name="dateSortie" type="date"/>
        </sequence>
    </complexType>

</schema>